package com.dev.quikkkk.enums;

import lombok.Getter;
import org.springframework.http.HttpStatus;

import static org.springframework.http.HttpStatus.BAD_REQUEST;
import static org.springframework.http.HttpStatus.CONFLICT;
import static org.springframework.http.HttpStatus.FORBIDDEN;
import static org.springframework.http.HttpStatus.NOT_FOUND;
import static org.springframework.http.HttpStatus.UNAUTHORIZED;

@Getter
public enum ErrorCode {
    USER_NOT_FOUND("USER_NOT_FOUND", "User not found with id %s", NOT_FOUND),
    INTERNAL_SERVER_ERROR("INTERNAL_SERVER_ERROR", "Internal Server Error", HttpStatus.INTERNAL_SERVER_ERROR),
    INVALID_CREDENTIALS("INVALID_CREDENTIALS", "Invalid Credentials", UNAUTHORIZED),
    ACCOUNT_DISABLED("ACCOUNT_DISABLED", "Account Disabled", FORBIDDEN),
    TOKEN_EXPIRED("TOKEN_EXPIRED", "Token Expired", UNAUTHORIZED),
    TOKEN_INVALID("TOKEN_INVALID", "Invalid Token", UNAUTHORIZED),
    TOKEN_BLACKLISTED("TOKEN_BLACKLISTED", "Token Blacklisted", UNAUTHORIZED),
    REFRESH_TOKEN_REQUIRED("REFRESH_TOKEN_REQUIRED", "Token Required", BAD_REQUEST),
    INVALID_REFRESH_TOKEN("INVALID_REFRESH_TOKEN", "Invalid Refresh Token", UNAUTHORIZED),
    EMAIL_ALREADY_EXISTS("EMAIL_ALREADY_EXISTS", "Email Already Exists", CONFLICT),
    EMAIL_ALREADY_VERIFIED("EMAIL_ALREADY_VERIFIED", "Email Already Verified", BAD_REQUEST),
    VERIFICATION_TOKEN_INVALID("VERIFICATION_TOKEN_INVALID", "Verification Token Invalid", BAD_REQUEST),
    VERIFICATION_TOKEN_EXPIRED("VERIFICATION_TOKEN_EXPIRED", "Verification Token Expired", BAD_REQUEST),
    VERIFICATION_TOKEN_TYPE_INVALID("VERIFICATION_TOKEN_TYPE_INVALID", "Verification Token Type Invalid", BAD_REQUEST),
    RESEND_TOO_FREQUENT("RESEND_TOO_FREQUENT", "Verification email was sent recently. Try again later", HttpStatus.TOO_MANY_REQUESTS),
    VALIDATION_ERROR("VALIDATION_ERROR", "Validation failed", BAD_REQUEST),
    PASSWORD_MISMATCH("PASSWORD_MISMATCH", "Password and confirm password do not match", BAD_REQUEST),
    UNAUTHORIZED_USER("UNAUTHORIZED_USER", "Unauthorized", FORBIDDEN),
    CLIENT_PROFILE_ALREADY_EXISTS("CLIENT_PROFILE_ALREADY_EXISTS", "Client Profile Already Exists", CONFLICT),
    CLIENT_PROFILE_NOT_FOUND("CLIENT_PROFILE_NOT_FOUND", "Client Profile Not Found", NOT_FOUND),
    CLIENT_PROFILE_DEACTIVATED("CLIENT_PROFILE_DEACTIVATED", "Client Profile Deactivated", FORBIDDEN),
    TRAINER_PROFILE_ALREADY_EXISTS("TRAINER_PROFILE_ALREADY_EXISTS", "Trainer Profile Already Exists", CONFLICT),
    TRAINER_PROFILE_NOT_FOUND("TRAINER_PROFILE_NOT_FOUND", "Trainer Profile Not Found", NOT_FOUND),
    TRAINER_PROFILE_DEACTIVATED("TRAINER_PROFILE_DEACTIVATED", "Trainer Profile Deactivated", FORBIDDEN),
    SPECIALIZATION_NOT_FOUND("SPECIALIZATION_NOT_FOUND", "Specialization Not Found", NOT_FOUND),
    SPECIALIZATION_ALREADY_EXISTS("SPECIALIZATION_ALREADY_EXISTS", "Specialization Already Exists", CONFLICT),
    SPECIALIZATION_NOT_FOUND_OR_INACTIVE("SPECIALIZATION_NOT_FOUND_OR_INACTIVE", "Specialization Not Found or Inactive", NOT_FOUND),
    MEMBERSHIP_VISITS_REQUIRED("MEMBERSHIP_VISITS_REQUIRED", "Membership Visits Required", BAD_REQUEST),
    MEMBERSHIP_DURATION_REQUIRED("MEMBERSHIP_DURATION_REQUIRED", "Membership Duration Required", BAD_REQUEST),
    MEMBERSHIP_NOT_FOUND("MEMBERSHIP_NOT_FOUND", "Membership Not Found", NOT_FOUND),
    MEMBERSHIP_ALREADY_ACTIVATED("MEMBERSHIP_ALREADY_ACTIVATED", "Membership Already Activated", FORBIDDEN),
    MEMBERSHIP_CANNOT_BE_FROZEN("MEMBERSHIP_CANNOT_BE_FROZEN", "Membership Cannot be Frozen", BAD_REQUEST),
    MEMBERSHIP_NOT_FROZEN("MEMBERSHIP_NOT_FROZEN", "Membership Not Frozen", BAD_REQUEST),
    MEMBERSHIP_INVALID_STATUS("MEMBERSHIP_INVALID_STATUS", "Membership Invalid Status", CONFLICT),
    MEMBERSHIP_TYPE_NOT_EXTENDABLE("MEMBERSHIP_TYPE_NOT_EXTENDABLE", "Membership Type Not Extendable", BAD_REQUEST),
    MEMBERSHIP_STATUS_NOT_EXTENDABLE("MEMBERSHIP_STATUS_NOT_EXTENDABLE", "Membership Status Not Extendable", CONFLICT),
    MEMBERSHIP_EXTEND_DURATION_INVALID("MEMBERSHIP_EXTEND_DURATION_INVALID", "Membership Extend Duration Invalid", BAD_REQUEST),
    MEMBERSHIP_STATUS_NOT_ACTIVATABLE("MEMBERSHIP_STATUS_NOT_ACTIVATABLE", "Membership Status Not Activatable", FORBIDDEN),
    CLIENT_ALREADY_HAS_ACTIVE_MEMBERSHIP("CLIENT_ALREADY_HAS_ACTIVE_MEMBERSHIP", "Client Already Has Active", CONFLICT),
    MEMBERSHIP_TYPE_NOT_FREEZABLE("MEMBERSHIP_TYPE_NOT_FREEZABLE", "Membership Type Not Freezable", BAD_REQUEST),
    MEMBERSHIP_END_DATE_MISSING("MEMBERSHIP_END_DATE_MISSING", "Membership End Date Missing", BAD_REQUEST),
    MEMBERSHIP_STATUS_NOT_FREEZABLE("MEMBERSHIP_STATUS_NOT_FREEZABLE", "Membership Status Not Freezable", BAD_REQUEST),
    MEMBERSHIP_STATUS_NOT_CANCELLABLE("MEMBERSHIP_STATUS_NOT_CANCELLABLE", "Membership Status Not Cancelled", BAD_REQUEST),
    NO_ACTIVE_MEMBERSHIP("NO_ACTIVE_MEMBERSHIP", "No Active Membership", NOT_FOUND),
    MEMBERSHIP_FROZEN("MEMBERSHIP_FROZEN", "Membership Frozen", FORBIDDEN),
    VISITS_LIMIT_REACHED("VISITS_LIMIT_REACHED", "Visits limit Reached", BAD_REQUEST),
    MEMBERSHIP_EXPIRED("MEMBERSHIP_EXPIRED", "Membership Expired", BAD_REQUEST),
    PERSONAL_TRAINING_MAX_ONE_PARTICIPANT("PERSONAL_TRAINING_MAX_ONE_PARTICIPANT", "Personal Training Max One Participant", BAD_REQUEST),
    GROUP_TRAINING_MIN_TWO_PARTICIPANTS("GROUP_TRAINING_MIN_TWO_PARTICIPANTS", "Group Training Min Two Participants", BAD_REQUEST),
    START_TIME_IN_PAST("START_TIME_IN_PAST", "Start time in past", BAD_REQUEST),
    SESSION_NOT_FOUND("SESSION_NOT_FOUND", "Session Not Found", NOT_FOUND),
    SESSION_NOT_JOINABLE("SESSION_NOT_JOINABLE", "Session Not Joinable", BAD_REQUEST),
    CLIENT_ALREADY_JOINED_SESSION("CLIENT_ALREADY_JOINED_SESSION", "Client Already Joined Session", CONFLICT),
    SESSION_IS_FULL("SESSION_IS_FULL", "Session Is Full", BAD_REQUEST),
    SESSION_CHECKIN_TOO_EARLY("SESSION_CHECKIN_TOO_EARLY", "Session Checkin Too Early", BAD_REQUEST),
    SESSION_ALREADY_FINISHED("SESSION_ALREADY_FINISHED", "Session Already Finished", BAD_REQUEST),
    CLIENT_ALREADY_CHECKED_IN("CLIENT_ALREADY_CHECKED_IN", "Client Already Checked In", FORBIDDEN),
    MEMBERSHIP_CANCELLED("MEMBERSHIP_CANCELLED", "Membership Cancelled", BAD_REQUEST),
    CLIENT_MEMBERSHIP_NOT_FOUND("CLIENT_MEMBERSHIP_NOT_FOUND", "Client Membership Not Found", NOT_FOUND),
    EXERCISE_NOT_FOUND("EXERCISE_NOT_FOUND", "Exercise Not Found", NOT_FOUND),
    EXERCISE_ALREADY_ACTIVATED("EXERCISE_ALREADY_ACTIVATED", "Exercise Already Activated", BAD_REQUEST),
    EXERCISE_ALREADY_DEACTIVATED("EXERCISE_ALREADY_DEACTIVATED", "Exercise Already Deactivated", FORBIDDEN),
    EXERCISE_DEACTIVATED("EXERCISE_DEACTIVATED", "Exercise Deactivated", FORBIDDEN),
    INVALID_WORKOUT_DAY("INVALID_WORKOUT_DAY", "Invalid Workout Day", BAD_REQUEST),
    DUPLICATE_EXERCISE_ORDER("DUPLICATE_EXERCISE_ORDER", "Duplicate Exercise Order", BAD_REQUEST),
    WORKOUT_PLAN_NOT_FOUND("WORKOUT_PLAN_NOT_FOUND", "Workout Plan Not Found", NOT_FOUND),
    WORKOUT_PLAN_DEACTIVATED("WORKOUT_PLAN_DEACTIVATED", "Workout Plan Deactivated", FORBIDDEN),
    WORKOUT_PLAN_FORBIDDEN("WORKOUT_PLAN_FORBIDDEN", "Forbidden", FORBIDDEN),
    WORKOUT_PLAN_ALREADY_ACTIVATED("WORKOUT_PLAN_ALREADY_ACTIVATED", "Workout Plan Already Activated", BAD_REQUEST),
    WORKOUT_PLAN_ALREADY_DEACTIVATED("WORKOUT_PLAN_ALREADY_DEACTIVATED", "Workout Plan Deactivated", BAD_REQUEST),
    TOO_MANY_REQUESTS("TOO_MANY_REQUESTS", "Too many requests", HttpStatus.TOO_MANY_REQUESTS),
    EXERCISE_ALREADY_IN_PLAN("EXERCISE_ALREADY_IN_PLAN", "Exercise Already In Plan", BAD_REQUEST),
    PLAN_DONT_HAVE_EXERCISE("PLAN_DONT_HAVE_EXERCISE", "Plan don't have exercise", BAD_REQUEST),
    ORDER_INDEX_DUPLICATED("ORDER_INDEX_DUPLICATED", "Order Index Duplicated", CONFLICT),
    PLAN_EXERCISE_NOT_FOUND("PLAN_EXERCISE_NOT_FOUND", "Plan Exercise Not Found", NOT_FOUND),
    PLAN_EXERCISE_NOT_IN_PLAN("PLAN_EXERCISE_NOT_IN_PLAN", "Plan Exercise Not In Plan", BAD_REQUEST),
    PLAN_EXERCISE_DAY_MISMATCH("PLAN_EXERCISE_DAY_MISMATCH", "Plan Exercise Day Mismatch", BAD_REQUEST),
    PLAN_EXERCISE_ALREADY_EXISTS("PLAN_EXERCISE_ALREADY_EXISTS", "Plan Exercise Already Exists", BAD_REQUEST),
    PLAN_EXERCISE_DAY_EMPTY("PLAN_EXERCISE_DAY_EMPTY", "Plan Exercise Day Empty", BAD_REQUEST),
    PLAN_EXERCISE_ORDER_DUPLICATED("PLAN_EXERCISE_ORDER_DUPLICATED", "Plan Exercise Order Duplicated", BAD_REQUEST),
    TRAINER_SESSION_OVERLAP("TRAINER_SESSION_OVERLAP", "You already have a session scheduled at this time", BAD_REQUEST),
    CLIENT_ASSIGNMENT_NOT_FOUND("CLIENT_ASSIGNMENT_NOT_FOUND", "Client Assignment Not Found", NOT_FOUND),
    INVALID_ASSIGNMENT_STATUS("INVALID_ASSIGNMENT_STATUS", "Invalid Assignment Status", BAD_REQUEST),
    SESSION_CLOSED("SESSION_CLOSED", "Session closed", FORBIDDEN),
    WORKOUT_LOG_NOT_FOUND("WORKOUT_LOG_NOT_FOUND", "Workout Log Not Found", NOT_FOUND),
    WORKOUT_LOG_ACCESS_DENIED("WORKOUT_LOG_ACCESS_DENIED", "Access to this workout log is denied", FORBIDDEN),
    FOOD_NOT_FOUND("FOOD_NOT_FOUND", "Food Not Found", NOT_FOUND),
    DUPLICATE_RESOURCE("DUPLICATE_RESOURCE", "Duplicate Resource", CONFLICT),
    FORBIDDEN_ACCESS("FORBIDDEN_ACCESS", "Forbidden", FORBIDDEN),
    MEAL_PLAN_NOT_FOUND("MEAL_PLAN_NOT_FOUND", "Meal plan Not Found", NOT_FOUND),
    MEAL_NOT_FOUND("MEAL_NOT_FOUND", "Meal not Found", NOT_FOUND),
    MEAL_ALREADY_COMPLETED("MEAL_ALREADY_COMPLETED", "Meal Already Completed", BAD_REQUEST),
    BODY_MEASUREMENT_NOT_FOUND("BODY_MEASUREMENT_NOT_FOUND", "Body measurement Not Found", NOT_FOUND),
    ROLE_NOT_FOUND("ROLE_NOT_FOUND", "Role not found", NOT_FOUND),
    GOAL_NOT_FOUND("GOAL_NOT_FOUND", "Goal not found", NOT_FOUND),
    GOAL_ALREADY_COMPLETED("GOAL_ALREADY_COMPLETED", "Goal already completed", BAD_REQUEST),
    GOAL_NOT_ACTIVE("GOAL_NOT_ACTIVE", "Goal is not active", BAD_REQUEST),
    ACTIVE_GOAL_ALREADY_EXISTS("ACTIVE_GOAL_ALREADY_EXISTS", "Active goal of this type already exists", CONFLICT),
    PERSONAL_RECORD_NOT_FOUND("PERSONAL_RECORD_NOT_FOUND", "Personal Record Not Found", NOT_FOUND),
    NOT_A_NEW_RECORD("NOT_A_NEW_RECORD", "New value is not better than current best value", BAD_REQUEST),
    CONCURRENT_UPDATE_ERROR("CONCURRENT_UPDATE_ERROR", "Resource was updated by another request. Please retry.", CONFLICT),
    ;

    private final String code;
    private final String defaultMessage;
    private final HttpStatus status;

    ErrorCode(String code, String defaultMessage, HttpStatus status) {
        this.code = code;
        this.defaultMessage = defaultMessage;
        this.status = status;
    }
}
