package com.dev.quikkkk.enums;

public enum NotificationType {
    SESSION_REMINDER,
    SESSION_CANCELLED,
    SESSION_RESCHEDULED,
    MEMBERSHIP_EXPIRING,
    MEMBERSHIP_EXPIRED,
    MEMBERSHIP_ACTIVATED,
    PAYMENT_SUCCESS,
    PAYMENT_FAILED,
    PAYMENT_REFUNDED,
    NEW_WORKOUT_PLAN,
    WORKOUT_COMPLETED,
    GOAL_ACHIEVED,
    MILESTONE_REACHED,
    NEW_MESSAGE,
    NEW_REVIEW,
    TRAINER_ASSIGNED,
    GENERAL_ANNOUNCEMENT,
    MAINTENANCE_SCHEDULED,
    PROFILE_UPDATE_REMINDER,
    MEASUREMENT_REMINDER
}
