spring:
  application:
    name: FitHub
  profiles:
    default: dev
  config:
    import: optional:file:env.properties
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          batch_size: 20
        order_updates: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: false
    validate-on-migrate: true
    encoding: UTF-8
    sql-migration-prefix: V
    sql-migration-separator: __
    sql-migration-suffixes: .sql
    table: flyway_schema_history
  task:
    execution:
      pool:
        core-size: 2
        max-size: 5
        queue-capacity: 100
      thread-name-prefix: async-

app:
  email:
    max-retry-attempts: 3
    retry-delay-minutes: 5
  security:
    disposable-email: 10minutemail,20minutemail,33mail,5ymail,anonbox,guerrillamail,mailinator,maildrop,mailnesia,moakt,my10minutemail,throwawaymail,trashmail,temp-mail,tempmail,truemail,yopmail

file:
  upload:
    video-dir: uploads/videos
    image-dir: uploads/images

logging:
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/fithub.log

tron:
  api:
    url: https://nile.trongrid.io
  wallet:
    address: ${TEST_WALLET:}

telegram:
  bot:
    token: ${TELEGRAM_TOKEN:}
    api-url: ${API_TELEGRAM_URL:https://api.telegram.org/bot}

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
