spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/fithub_testdb?prepareThreshold=0
    username: testuser
    password: testpassword

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  flyway:
    enabled: true
    clean-disabled: false

  data:
    redis:
      host: localhost
      port: 6379
      password:

  mail:
    host: localhost
    port: 1025
    username: test
    password: test

  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=100,expireAfterWrite=10m

app:
  email:
    max-retry-attempts: 3
    retry-delay-minutes: 1
  frontend:
    url: http://localhost:4200
  security:
    jwt:
      auto-generate: true
      access-token-expiration: 3600000
      refresh-token-expiration: 86400000
    disposable-email: mailinator,tempmail,guerrillamail
  cors:
    allowed-origins: http://localhost:4200,http://localhost:5173

logging:
  level:
    root: WARN
    com.dev.quikkkk: DEBUG
    org.springframework.security: WARN
    org.hibernate: WARN

tron:
  api:
    url: https://nile.trongrid.io
  wallet:
    address: ${TEST_WALLET:}

telegram:
  bot:
    token: ${TELEGRAM_TOKEN:}
    api-url: ${API_TELEGRAM_URL:https://api.telegram.org/bot}
